### ISSUE TITLE
render js code with embedded data

### ISSUE THREAD

**Issue by RKaczmarek** [daboth/pive#1]
It would be nice to have the ability to generate only one js file containing the code to generate the chart, where the data is embedded.

In this case D3 would not fetch the data json via ajax (json or csv).

**Comment by daboth** [comment]
I'll look into it. Pives chart templates process their dataset completely even before drawing chunks of it to determine max-values anyway. The only issues occuring to me are the really large js files when _hardcoding_ (or in this case, _templating_) the dataset into them. They also won't be dynamically anymore. I need to evaluate this. Thanks for your contribution.
